sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
install:
  - npm install && npm install -g gulp-cli
before_script:
  - npm prune
script: gulp build
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
