language: node_js
node_js:
  - '10'
install:
  - yarn add global eslint
  - yarn add global babel-eslint
  - yarn add global eslint-plugin-react
  - yarn add global eslint-plugin-mocha
  - yarn add global eslint-config-synacor
script:
  - yarn run lint
  - yarn run test
cache: yarn
