language: java

jdk:
    - oraclejdk7

install:
    - true

script: 
    - mvn clean install -Dmaven.test.failure.ignore=true

after_success:
    - mvn cobertura:cobertura coveralls:cobertura -Dmaven.test.failure.ignore=true