language: node_js
node_js:
- 'stable'
env:
  global:
  - secure: "aJ5yN0TQJZFF0gdp2+WHq9nLvbZqs7T5/4owiS0eZ+DjO0+8sMc2prW1O56t/raY2+BdijPePwTQVxRpkOYX4YvDE7jDfARESKr15x8LUijdl6Fo47TM0l8w742zpg5bu3D2z8UoAQJxAlli7MsLfz9a4pi6AgBdkfuLqxqpXFo="
script:
- npm run build
before_deploy:
- echo "registry=https://registry.npmjs.org/" > .npmrc
- echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" >> .npmrc
- echo "//registry.npmjs.org/:username=mboudreau" >> .npmrc
- echo "//registry.npmjs.org/:email=michelboudreau@gmail.com" >> .npmrc
- echo "//registry.npmjs.org/:always-auth=true" >> .npmrc
- cp README.md package.json LICENSE build/
deploy:
- provider: script
  script: npm publish build/ --access public
  skip_cleanup: true
  on:
    branch: master
    tags: true
after_failure:
- find . -iname '*.log' -print0 | xargs -0 cat