/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Date */

#ifndef _Included_Date
#define _Included_Date
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Date
 * Method:    printDate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Date_printDate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
