/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeSumDemo */

#ifndef _Included_NativeSumDemo
#define _Included_NativeSumDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeSumDemo
 * Method:    sum
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_NativeSumDemo_sum
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
