/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringAdd */

#ifndef _Included_StringAdd
#define _Included_StringAdd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringAdd
 * Method:    add
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StringAdd_add
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
