/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringStuff */

#ifndef _Included_StringStuff
#define _Included_StringStuff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringStuff
 * Method:    totalChars
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StringStuff_totalChars
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
