title: "Button (element)"
notes: "Todo: documentation..."
name: "button"
context:
  text: "Button"
collated: true
variants:
  -
    name: "small"
    context:
      modifier: "small"
      text: "Small Button"
  -
    name: "large"
    context:
      modifier: "large"
      text: "Large Button"
