"""empty message

Revision ID: 13831eb11706
Revises: None
Create Date: 2016-03-12 21:17:15.147816

"""

# revision identifiers, used by Alembic.
revision = '13831eb11706'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
