"""empty message

Revision ID: 20db3d5dab9e
Revises: 9ccf38731dfb
Create Date: 2016-06-17 14:49:49.981963

"""

# revision identifiers, used by Alembic.
revision = '20db3d5dab9e'
down_revision = '9ccf38731dfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
