"""empty message

Revision ID: 29047949eb97
Revises: b45ca477abcb
Create Date: 2016-06-17 14:48:43.729342

"""

# revision identifiers, used by Alembic.
revision = '29047949eb97'
down_revision = 'b45ca477abcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
