"""empty message

Revision ID: 890f0f2ba1d1
Revises: 13831eb11706
Create Date: 2016-06-17 14:06:45.353715

"""

# revision identifiers, used by Alembic.
revision = '890f0f2ba1d1'
down_revision = '13831eb11706'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=64), nullable=True))
    op.drop_column('user', 'new_field')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('new_field', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
