"""empty message

Revision ID: 9ccf38731dfb
Revises: 29047949eb97
Create Date: 2016-06-17 14:49:29.948710

"""

# revision identifiers, used by Alembic.
revision = '9ccf38731dfb'
down_revision = '29047949eb97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    ### end Alembic commands ###
