"""empty message

Revision ID: b45ca477abcb
Revises: 41fc015bc30c
Create Date: 2016-06-17 14:48:23.391721

"""

# revision identifiers, used by Alembic.
revision = 'b45ca477abcb'
down_revision = '41fc015bc30c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    ### end Alembic commands ###
