"""empty message

Revision ID: d2c62a51503a
Revises: 20db3d5dab9e
Create Date: 2016-06-17 14:58:02.098278

"""

# revision identifiers, used by Alembic.
revision = 'd2c62a51503a'
down_revision = '20db3d5dab9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    ### end Alembic commands ###
