// Generated by CoffeeScript 1.12.7
(function() {
  var block, i, img, len, ref;

  document.addEventListener("DOMContentLoaded", function() {
    return document.body.classList.add('loaded-document');
  });

  ref = document.querySelectorAll('.block');
  for (i = 0, len = ref.length; i < len; i++) {
    block = ref[i];
    img = new Image();
    img.block = block;
    img.onload = function() {
      return this.block.classList.add('loaded-image');
    };
    img.src = getComputedStyle(block).backgroundImage.slice(4, -1).replace(/"/g, "");
    block.addEventListener('click', function() {
      this.classList.add('clicked');
      return this.classList.toggle('loaded-image');
    });
  }

}).call(this);
