// Generated by CoffeeScript 1.12.7
(function() {
  var updateLocation;

  updateLocation = function() {
    var string, text;
    text = $(".current p").text();
    if (text.length) {
      text = text.split(",");
      string = "Weather for " + text[0] + ", " + text[1].split(" ")[1];
    } else {
      string = "No location selected.";
    }
    return $("#save-and-return").slideUp(200, $("#save-and-return").html(string).slideDown(200));
  };

  $("body").on("click", ".location", function() {
    $(".location").removeClass("current");
    $(this).addClass("current");
    return updateLocation();
  });

  $("#add").click(function() {
    var $zip;
    $zip = $("#zip");
    $(".location").removeClass("current");
    $("h2").after("<div class='location current new' style='opacity: 0; display: none;'><p>New City, CA <span class='zip'>" + ($zip.val()) + "</span><span class='remove'>&times;</span></p></div>");
    $zip.val("");
    $("div.location.new").slideDown().css("opacity", 1).removeClass("new");
    $(this).addClass("inactive");
    return updateLocation();
  });

  $("body").on("click", ".remove", function() {
    return $(this).parents(".location").slideUp(400, function() {
      $(".location").removeClass("current");
      $(this).parents(".location").detach();
      $(".content .location:visible").first().addClass("current");
      return updateLocation();
    });
  });

  $("#zip").keyup(function() {
    var val;
    val = $(this).val();
    console.log(val);
    if (val.length === 5 && /^\d+$/.test(val)) {
      return $("#add").removeClass("inactive");
    } else {
      return $("#add").addClass("inactive");
    }
  });

  $("#zip").keypress(function(e) {
    var val;
    val = $(this).val();
    if (val.length === 5 && /^\d+$/.test(val) && e.which === 13) {
      return $("#add").trigger("click");
    }
  });

  $(document).ready(function() {
    return updateLocation();
  });

}).call(this);
