// Generated by CoffeeScript 1.12.7
(function() {
  $.ajax("/products.json", {
    type: "GET",
    dataType: "json",
    success: function(data, status, XHR) {
      var html, template;
      template = Handlebars.compile($("#product_template").html());
      html = template({
        products: data
      });
      return $('body').append(html);
    },
    error: function(XHR, status, errorThrown) {
      var html, template;
      template = Handlebars.compile($("#error_template").html());
      html = template({
        error: "Can't load data: " + errorThrown
      });
      return $('body').append(html);
    }
  });

}).call(this);
