###################################
# Automatically generated by qmake
###################################

TEMPLATE = app
TARGET +=
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += byteconverterdialog.ui
SOURCES += main.cpp byteconverterdialog.cpp
HEADERS += byteconverterdialog.h

DESTDIR = ../../../bin/chapter03
