#####################################
# Automatically generated by qmake
#####################################

TEMPLATE = app
CONFIG -= moc
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp

DESTDIR = ../../../bin/chapter05
