service: contact

provider:
  name: aws
  stage: production
  region: eu-west-1
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

functions:
  contact:
    handler: handler.contact
    events:
      - http:
          method: post
          path: contact
          cors: true
