options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - '**/vendor/**/*.scss'
    - '**/tests/**/*.scss'
rules:
  attribute-quotes:
    - 2
    -
      include: true
  bem-depth:
    - 2
    -
      max-depth: 1
  border-zero:
    - 2
    -
      convention: '0'
  brace-style:
    - 2
    -
      style: '1tbs'
      allow-single-line: false
  class-name-format:
    - 2
    -
      allow-loading-underscore: false
      convention: hyphenatedbem
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false
  empty-args:
    - 2
    -
      include: false
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    -
      include: true
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: camelcase
  hex-length:
    - 2
    -
      style: long
  hex-notation:
    - 2
    -
      style: uppercase
  id-name-format:
    - 2
    -
      allow-loading-underscore: false
      convention: hyphenatedlowercase
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: true
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedbem
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    -
      max-depth: 4
  no-attribute-selectors: 1
  no-color-keywords: 2
  no-color-literals: 0
  no-combinators: 1
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 1
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 0
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-transition-all: 2
  no-universal-selectors: 1
  no-url-protocols: 2
  no-vendor-prefixes:
    - 2
    -
      excluded-identifiers:
        - 'webkit'
        - 'moz'
      ignore-non-standard: true
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedbem
  property-sort-order:
    - 2
    -
      order:
        - 'content'

        - 'outline'
        - 'outline-color'
        - 'outline-offset'
        - 'outline-style'
        - 'outline-width'

        - 'z-index'
        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'

        - 'display'
        - 'align-items'
        - 'align-self'
        - 'flex'
        - 'flex-basis'
        - 'flex-direction'
        - 'flex-flow'
        - 'flex-grow'
        - 'flex-shrink'
        - 'flex-wrap'
        - 'justify-content'
        - 'order'

        - 'background'
        - 'background-attachment'
        - 'background-clip'
        - 'background-color'
        - 'background-image'
        - 'background-position'
        - 'background-repeat'
        - 'background-size'

        - 'width'
        - 'max-width'
        - 'min-width'

        - 'height'
        - 'max-height'
        - 'min-height'

        - 'border'
        - 'border-color'
        - 'border-top'
        - 'border-right'
        - 'border-bottom'
        - 'border-left'
        - 'border-radius'

        - 'box-shadow'

        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'
        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'
        - 'box-sizing'

        - 'float'
        - 'clear'

        - 'columns'
        - 'column-gap'
        - 'column-fill'
        - 'column-rule'
        - 'column-span'
        - 'column-count'
        - 'column-width'

        - 'transform'
        - 'transform-origin'

        - 'transition'
        - 'transition-delay'
        - 'transition-duration'
        - 'transition-property'
        - 'transition-timing-function'

        - 'color'
        - 'font'
        - 'font-family'
        - 'font-size'
        - 'font-smoothing'
        - 'font-style'
        - 'font-variant'
        - 'font-weight'
        - 'letter-spacing'
        - 'line-height'
        - 'text-align'
        - 'text-decoration'
        - 'text-indent'
        - 'text-overflow'
        - 'text-rendering'
        - 'text-shadow'
        - 'text-transform'
        - 'text-wrap'

        - 'white-space'
        - 'word-spacing'

        - 'overflow'
        - 'overflow-x'
        - 'overflow-y'

        - 'opacity'
        - 'vertical-align'
        - 'visibility'
        - 'cursor'
      ignore-custom-properties: true
  pseudo-element: 0
  quotes:
    - 2
    - style: single
  shorthand-values: 3
  single-line-per-selector: 2
  space-after-bang:
    - 2
    -
      include: false
  space-after-colon:
    - 2
    -
      include: true
  space-after-comma:
    - 2
    -
      include: true
  space-around-operator:
    - 2
    -
      include: true
  space-before-bang:
    - 2
    -
      include: true
  space-before-brace:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  space-between-parens:
    - 2
    -
      include: false
  trailing-semicolon:
    - 2
    -
      include: true
  url-quotes: 2
  variable-for-property: 0
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit:
    - 2
    -
      include: false