##########################################
# Automatically generated by qmake (2.00a)
##########################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += rotationwidget.h
SOURCES += main.cpp rotationwidget.cpp

DESTDIR = ../../../bin/chapter10
