# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 572ba87bf04a18beb4eaa531d7423a47422fc6e2e52942289101c52cf2485b015348fb8fd4280ef7b20ddd7c0ac7a7d77726bc344396c913fb51703cf59f0f86

test:
  secret_key_base: 7750681911de7de47aff700f5fc90a46c870cde2ed24ed67bb7791520bc4a70cdd8804dcc801b2178d7330f52abcb7f91bf7162776de61f2902c3eafd5c9f5cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
