#####################################
# Automatically generated by qmake
#####################################

TEMPLATE = app
CONFIG -= moc
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp paintwidget.cpp
HEADERS += paintwidget.h

DESTDIR = ../../../bin/chapter10
