/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AirSnortWindow (void);
GtkWidget* create_AboutDlg (void);
GtkWidget* create_ListPopup (void);
GtkWidget* create_GpsDialog (void);
