##################################
# Automatically generated by qmake
##################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .
QT =

# Input
SOURCES += main.cpp

DESTDIR = ../../../bin/appendixAlgorithmen
