###################################
# Automatically generated by qmake
###################################

TEMPLATE = app
TARGET +=
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += d2clabel.h
SOURCES += d2clabel.cpp main.cpp


DESTDIR = ../../../bin/chapter07
