# A sample Guardfile
# More info at https://github.com/guard/guard#readme

## Uncomment and set this to only include directories you want to watch
# directories %w(app lib config test spec features) \
#  .select{|d| Dir.exists?(d) ? d : UI.warning("Directory #{d} does not exist")}

## Note: if you are using the `directories` clause above and you are not
## watching the project directory ('.'), then you will want to move
## the Guardfile to a watched dir and symlink it back, e.g.
#
#  $ mkdir config
#  $ mv Guardfile config/
#  $ ln -s config/Guardfile .
#
# and, you'll have to watch "config/Guardfile" instead of "Guardfile"

# coffeescript_options = {
# input: 'coffeescript',
# output: 'javascript',
# patterns: [%r{^javascript/(.+\.(?:coffee|coffee\.md|litcoffee))$}]
#}

#guard 'coffeescript', coffeescript_options do
# coffeescript_options[:patterns].each { |pattern| watch(pattern) }
#end

guard 'coffeescript', :input => 'coffeescript', :output => 'javascript' do
  watch(%r{coffeescript/(.+\.coffee)})
end

guard 'coffeescript', :input => 'coffeescript', :output => 'javascript'