######################################################################
# Automatically generated by qmake (2.01a) Mo Sep 3 22:12:20 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
