// Generated by CoffeeScript 1.10.0
(function() {
  var generateStars, starHtml;

  $(document).ready(function() {
    var box, boxHTML, parsedHTML;
    box = $('.skill-box');
    boxHTML = box.html();
    parsedHTML = boxHTML.replace(/\{\{(.+)\}\}/g, function(match, stars) {
      return "<span class=\"stars\">" + (generateStars(stars)) + "</span>";
    });
    return box.html(parsedHTML);
  });

  starHtml = function(str) {
    return "<i class=\"fa fa-star" + (str != null ? str : '') + "\"></i>";
  };

  generateStars = function(stars) {
    var args, fullStars, hstar, nstars, ostars, ref, res, totalStars;
    args = stars.split('/');
    totalStars = (ref = args[1]) != null ? ref : 5;
    nstars = parseInt(args[0]);
    fullStars = Math.floor(nstars);
    hstar = 2 * (nstars - fullStars);
    ostars = totalStars - fullStars - hstar;
    res = "";
    _.times(fullStars, function() {
      return res += starHtml();
    });
    _.times(ostars, function() {
      return res += starHtml(' white');
    });
    return res;
  };

}).call(this);
