###################################
# Automatically generated by qmake
###################################

TEMPLATE = app
TARGET += .
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += byteconverterdialog.ui
SOURCES += main.cpp

DESTDIR = ../../../bin/chapter03
