######################################################################
# Automatically generated by qmake (2.01a) Di Sep 4 00:01:15 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
