const ADD_ELEMENT = 'ADD_ELEMENT';

const CHANGE_ELEMENTS_MENU = 'CHANGE_ELEMENTS_MENU';
const DELETE_ELEMENT = 'DELETE_ELEMENT';
const TOGGLE_ELEMENTS_MENU = 'TOGGLE_ELEMENTS_MENU';

const TOGGLE_PAGES_MENU = 'TOGGLE_PAGES_MENU';

const TOGGLE_RESPONSIVE_MENU = 'TOGGLE_RESPONSIVE_MENU';
const DECREASE_CONTENT_SIZE = 'DECREASE_CONTENT_SIZE';
const CHANGE_CONTENT_SIZE = 'CHANGE_CONTENT_SIZE';
const INCREASE_CONTENT_SIZE = 'INCREASE_CONTENT_SIZE';

const ADD_PAGE = 'ADD_PAGE';
const DELETE_PAGE = 'DELETE_PAGE';
const CHANGE_PAGE = 'CHANGE_PAGE';

export {
  ADD_ELEMENT,
  ADD_PAGE,
  DECREASE_CONTENT_SIZE,
  CHANGE_CONTENT_SIZE,
  CHANGE_ELEMENTS_MENU,
  CHANGE_PAGE,
  DELETE_ELEMENT,
  DELETE_PAGE,
  INCREASE_CONTENT_SIZE,
  TOGGLE_ELEMENTS_MENU,
  TOGGLE_PAGES_MENU,
  TOGGLE_RESPONSIVE_MENU,
};
