const BLOCK_ELEMENTS = {};

const FORM_ELEMENTS = {};

const TEXT_ELEMENTS = {};

const LAYOUT_ELEMENTS = {
  COLUMN_ELEMENT: 'COLUMN_ELEMENT',
  FOOTER_ELEMENT: 'FOOTER_ELEMENT',
  HEADER_ELEMENT: 'HEADER_ELEMENT',
  ROW_ELEMENT: 'ROW_ELEMENT',
  SECTION_ELEMENT: 'SECTION_ELEMENT',
};

export {
  BLOCK_ELEMENTS,
  FORM_ELEMENTS,
  LAYOUT_ELEMENTS,
  TEXT_ELEMENTS,
};
