jade-build:
  - 'jade'

sass-build:
  - 'sass'
  - 'csscomb'
  - 'postcss'
  - 'cssmin'

coffee-build:
  - 'coffee'
  - 'coffeelint'

copy-build:
  - copy:css
  - copy:font
  - copy:img

default:
  - 'jade-build'
  - 'sass-build'
  - 'coffee-build'
  - 'copy-build'
  - 'connect'
  - 'watch'