######################################################################
# Automatically generated by qmake (2.01a) Mo Sep 3 22:17:31 2007
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

DESTDIR = ../../../bin/chapter06
