##########################################
# Automatically generated by qmake (2.00a)
##########################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += piewidget.h
SOURCES += main.cpp piewidget.cpp

DESTDIR = ../../../bin/chapter10
